language: rust
sudo: false
git:
  submodules: false
cache: cargo

matrix:
  include:
    - rust: stable
    - os: osx
      rust: stable
    - rust: beta
    - rust: nightly

scripts:
  - cargo test
  - cargo test --release

notifications:
  email: false
