[workspace]
members = [".", "packer_derive"]

[package]
authors = ["Michael Zhang <iptq@protonmail.com>", "Nathan Ringo <remexre@protonmail.com>"]
description = "Pack static files into your binary at compile time"
documentation = "https://docs.rs/packer"
edition = "2018"
license = "MIT"
name = "packer"
readme = "README.md"
repository = "https://github.com/iptq/packer"
version = "0.2.0"

[dependencies]
lazy_static = "1.2"
packer_derive = { path = "packer_derive" }

[dev-dependencies]
sha2 = "0.8"
