[package]
name = "packer"
version = "0.1.0"
repository = "https://github.com/iptq/packer"
documentation = "https://docs.rs/packer"
description = "Pack static files into your binary at compile time"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dev-dependencies]
sha2 = "0.8"

[dependencies]
syn = { version = "0.15", features = ["derive"] }
quote = "0.6"
proc-macro2 = "0.4"
lazy_static = "1.1"
walkdir = "2.2"
