[package]
name = "embed"
version = "0.1.0"
description = "Modified version of rust-embed"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[lib]
proc-macro = true

[dev-dependencies]
sha2 = "0.7"

[dependencies]
syn = "0.11"
quote = "0.3"
lazy_static = "1.1"
walkdir = "2.2"
